name: Terraform Worflow

on: 
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  terraform-validate:
    uses: diegotony/gh-pipelines/.github/workflows/terraform-validate.yml@main
    if: github.event_name == 'pull_request'
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  terraform-plugin-tfsec:
    if: github.event_name == 'pull_request'
    uses: diegotony/gh-pipelines/.github/workflows/terraform-plugin-tfsec.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  terraform-plugin-tfdocs:
    if: github.event_name == 'pull_request'
    uses: diegotony/gh-pipelines/.github/workflows/terraform-plugin-tfdocs.yml@main

  semantic-release:
    uses: diegotony/gh-pipelines/.github/workflows/semantic-release.yml@main
    if: github.ref == 'refs/heads/main' 
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
