name: Terraform CI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  iac:
    permissions:
      id-token: write
      contents: read
    uses: diegotony/gh-pipelines/.github/workflows/terraform-plugin-terragrunt-apply.yml@main
    secrets:
      AWS_ACCESS_ROLE: ${{ secrets.AWS_ACCESS_ROLE }}
      AWS_DEFAULT_REGION: us-east-1
