name: Terraform CI

on: 
  pull_request:
    branches:
      - main


jobs:
  terraform-validate:
    uses: diegotony/gh-pipelines/.github/workflows/terraform-validate.yml@main
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  terraform-plugin-tfsec:
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    uses: diegotony/gh-pipelines/.github/workflows/terraform-plugin-tfsec.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  terraform-plugin-tfdocs:
    needs: terraform-validate
    if: github.ref == 'refs/heads/main' 
    uses: diegotony/gh-pipelines/.github/workflows/terraform-plugin-tfdocs.yml@main


