name: Terraform Worflow

on: 
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  terraform-module:
    uses: diegotony/gh-pipelines/.github/workflows/terraform-module.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      AWS_ACCESS_ROLE: ${{ secrets.AWS_ACCESS_ROLE }}
      AWS_DEFAULT_REGION: "us-east-1"
