name: Release Module

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    uses: diegotony/gh-pipelines/.github/workflows/semantic-release.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
